name: Generate Articles HTML

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install sumy nltk

      - name: Download NLTK punkt data
        run: python -c "import nltk; nltk.download('punkt')"

      - name: Generate HTML from CSV
        run: python generate_html.py

      - name: Commit and push HTML
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/articles.html
          git commit -m "Auto-generate articles.html from articles.csv" || echo "No changes to commit"
          git push
