name: Generate Articles HTML

permissions:
  contents: write

on:
  workflow_dispatch:   # Allows manual trigger
  push:
    branches: [main]

jobs:
  build-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install spaCy and model
        run: |
          pip install spacy
          python -m spacy download en_core_web_sm

      - name: Generate HTML from CSV
        run: python generate_html.py

      - name: Commit and push HTML
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/articles.html
          git stash
          git pull --rebase origin main
          git stash pop || true
          git add output/articles.html
          git commit -m "Auto-generate articles.html from articles.csv" || echo "No changes to commit"
          git push origin main
