name: Scrape Moore Czech News

on:
  schedule:
    # every day at 06:00 Europe/Prague (04:00 UTC)
    - cron:  '0 4 * * *'
  workflow_dispatch:   # manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scripts/scrape_moore_news.py

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update News.xlsx with new Moore-Czech releases"
          file_pattern: News.xlsx
